### ISSUE TITLE
Cycle secret keys and remove all secrets from this repo

### ISSUE THREAD

**Issue by jchubber** [CareerVillage/slack-moderation#3]
Example: 
https://github.com/CareerVillage/slack-moderation/blob/master/src/moderation/settings/development.py#L20

**Comment by mprunell** [comment]
@jchubber the production environment imports `production.py` which has different keys for social auth (not pushed to the repo). Those keys are from a local dev environment. I remember we used a test slack app, but I'm not sure how to access that. I'll try to remember and see if I can recycle.
